### ISSUE TITLE
onHeartbeat function gives error "failed 'TypeError':'can't subtract offset-naive and offset-aware datetimes'."

### ISSUE THREAD

**Issue by StevenBoelhouwer** [lokonli/slide-domoticz#1]
Row 296 the datetime.now() needs a timezone.
I've replaced the entire row with:
`diff = self._expiretoken - datetime.now(timezone.utc)`
Error in domoticz log is gone!

**Comment by lokonli** [comment]
That's what I used first as well. However, if the plugin is started a
second time somehow the datetime function doesn't work. I've found a
workaround but then there is no timezone information.
I'll try to find a better solution. If you have suggestions please let me
know.

**Comment by lokonli** [comment]
I've implemented a workaround which seems to work.

Can you test?

**Comment by StevenBoelhouwer** [comment]
Running new version, restarted Domoticz a couple times. No issues so far. Will keep an eye on it.

**Comment by lokonli** [comment]
Great.
I've released a new version, with better support for multiple slides. Could you test that one as well?

**Comment by StevenBoelhouwer** [comment]
No issues this far. Will probably be able to add the second Slide during the weekend to test that part.

**Comment by lokonli** [comment]
I assume this is solved.
