### ISSUE TITLE
Sill crashing

### ISSUE THREAD

**Issue by heggink** [lokonli/slide-domoticz#13]
Looks like the patch didn't work. After having debug on for a couple of days, I noticed the plugin still dies multiple connects even though I check for connecting(). Suspect that multiple parallel requests lead to these multiple connects and they in turn lead to a crash on the next disconnect.

Implemented my own semaphore and testing that now but it depends on how these requests are executed. Will report later.

**Comment by lokonli** [comment]
Maybe it's better to not make use of the 'keep alive' mechanism, but just close the connection, and create a new one for every request.

**Comment by heggink** [comment]
My concern is that it won't change anything: I have 6 slides. If I close them all as a group, 6 simultaneous connect requests will be sent to the plugin framework before it will be able to send the action. Something seems to be iffy with the framework where simultaneous requests are not handled properly.

I was about to send the author a question as well.
________________________________

**Comment by lokonli** [comment]
I think we can cache all the requests within the plugin.

**Comment by lokonli** [comment]
I can create a develop branch for this, but probably not before the weekend ...

**Comment by heggink** [comment]
Given that we are better off moving to the local API when that gets finished, I would not bother. I sent dnpwwo a message as there's probably some bug in the framework (should not crash to begin with). Let's see if my latest workaround works. If so then I'd rather focus on the local API. Slide did get funding so they should be able to continue for a while but better safe than sorry!
________________________________

**Comment by lokonli** [comment]
I guess you've seen that the local API is working. Did you try it already?
https://github.com/lokonli/slide-domoticz-local

**Comment by heggink** [comment]
Saw it. Didn't have the time as other prio's ATM. Also, they indicated there would be a v2 improved api with big changes right?


Herman Eggink

________________________________

**Comment by lokonli** [comment]
No idea.

**Comment by heggink** [comment]
I have not experienced any crashes with the latest changes.
