### ISSUE TITLE
New Domoticz blinds subsystem changed commands on 0% and 100%

### ISSUE THREAD

**Issue by bvhoesel** [lokonli/slide-domoticz#15]
Old construction was:
```
  %  Command
  0: Off
  1: Set Level
 99: Set Level
100: On
```
New situation is:
```
  %  Command
  0: Close
  1: Set Level
 99: Set Level
100: Open
```
Proposed change in plugin.py to be compatible with old and new situation could be:
```
Line       Code
219:       if (Command == 'Off' or Command == 'Close'):
221:       if (Command == 'On' or Command == 'Open'):
```

**Comment by lokonli** [comment]
Thanks, I'll make a fix.

**Comment by lokonli** [comment]
I had to switch Close and Open.

@bvhoesel Can you test latest version?

**Comment by bvhoesel** [comment]
As I already expected from your switch, this does not directly work for me. The suggested code came from the plugin.py I modified to get it working correctly for me.
In my Domoticz config your switch of Open and Close has 'weird' effects. For example 99% closes the curtain and 100% opens it fully.
The various blinds devices in Domoticz have newly added properties in the latest betas. In the device definition I tried enabling, previously disabled, combinations of 'Reverse Open/Close State' and 'Reverse Position:' properties.
I could not find a combination that resulted in the percentage slider to work 'consistently' from fully opening to fully closed (varying % from 0, 1-99 and 100) and the 'Open' and 'Close' actions on the switch device.
Reverting back to my initial proposed 'Open' en 'Closed' if statements I could get a consistent behavior when I enabled the 'Reverse Open/Close State'.
![Screenshot at 2022-10-14 10-11-29](https://user-images.githubusercontent.com/3183695/195796839-c96fc13e-266f-4c3c-8df9-40d18a31ef91.png)

You may see some weird/strange commands (open, close and level combinations) getting to the plugin but the curtains work as expected and Domoticz end user GUI even seems consistent.

**Comment by lokonli** [comment]
Ok, I'll do some more tests, thanks.
Probably Ive to turn around the percentage as well.

Op vr 14 okt. 2022 10:16 schreef bvhoesel ***@***.***>:

**Comment by lokonli** [comment]
ok, new update.
Fixed issue for newer Domoticz version (>14760)
For these Domoticz versions the blinds type has been changed to 'percentage + stop'

In Domoticz just use the default blinds type. Settings 'Reverse Open/Close State' and 'Reverse Position' should be deselected.

@bvhoesel Can you test?

**Comment by bvhoesel** [comment]
Tested the updated plugin against the latest build as of today: 14573 (not sure what the number >14760 references to).
Changed the device type to 'blinds + stop' and after realizing the percentages now are reversed (one curtain I am not fully opening) the curtains are working as expected.

Big thanks for the fix.

**Comment by lokonli** [comment]
The 14760 is my mistake: typo in the title. It should be 14560, and that is approximately the build number of the changes in Domoticz.
Thanks for testing.
