### ISSUE TITLE
Moving to a local API

### ISSUE THREAD

**Issue by heggink** [lokonli/slide-domoticz#8]
Hey lokonli,

I was contacted by the Slide guys the other day where we were discussing all sorts of things. One of them was my wish to not be dependent on external web services and control the slides locally. They mentioned that there is a beta API that allows you to do that over http. They will send me the info.

Would it be an option to build support for that? Supposedly, the interface is quite simple (uses simple http without security which is fine for me as my home network is completely secured)?

Thanks!

H

**Comment by sonar98** [comment]
I would really like support for that too.
