### ISSUE TITLE
Plugin & domoticz crash Plugin_ASIO

### ISSUE THREAD

**Issue by heggink** [lokonli/slide-domoticz#9]
Done a little digging and found the following:
crash happens when I switch a group of slides together
just before the crash, the connection is disconnected
the plugin then does an onCommand for every slide (6 in my case) leading to 6x slideRequest which calls self.myConn.Connect() 6x (all onCommands are handled in parallel).
All of that seems to be handled fine (6x IIM connected succesfully). Then a few messages received (onMessage with good content) and then a "Disconnect event received" from the plugin framework followed by an onDisconnect called.

Normally, that message is followed straight by an onMessage with a message ("Connection": 'close') but this doesn't happen and domoticz crashes. My suspicion is that the 6 parallel connects mess something up...

**Comment by lokonli** [comment]
Probably executing 6x connect can give some issues. I see there is no check on a 'connecting' state.

I'll try to make it more robust, by queuing the slideRequests until it's connected.

**Comment by heggink** [comment]
For now I made a simple adjustment to connect again in onDisconnect. Looking at the timings, the disconnects seem to happen every 40 minutes or so and the connect itself is pretty fast. Reconnecting on disconnect should ensure that the connection is back up before any bulk changes to the slides happen so it preempts these multi-connects.

If onDisconnect also gets called on plugin shutdown then that is not something I have looked at and can cause problems as well but only if I restart the plugin which is unusual so let's see. I'll report back on the progress.

It's a shame that there's always the compromise in open source between functionality (the great python plugin framework) and the resilience (it really should not crash with a segmentation fault). I have had discussions on that with some people who argue that it's a fact of life and you cannot foresee all situations causing these crashes. Agreed but clearly robust error handling is not part of it :-(...

**Comment by heggink** [comment]
For now, this reconnect on disconnect means that Domoticz has not crashed in nearly 6 days. Normally it would have already.

**Comment by lokonli** [comment]
Nice!
You made the change yourself already. Could you also make a PR (Pull Request)? Then I'll just merge your change.
or copy-paste your code here, and I'll make the change.

**Comment by heggink** [comment]
Done (I think, I don;t do these very often).
btw: there's also feedback from dnpwwo on the forum that needs a look. Haven't done that yet.

**Comment by heggink** [comment]
Bugger! another crash with a different error but still in Plugin_ASIO. looked at the message from dnpwwo and applied another change on line 230 replacing & with and. Did not change the statement itself (testing both connection and token in 1 go).
